language: python
python:
- "3.8"
# setup environment
env:
- DJANGO_VERSION=3.0.5
# install dependencies
install:
- pip install -r requirements.txt

#Nortifiactions

# run test scripts
script:
- python manage.py test 