# Generated by Django 3.0.6 on 2020-05-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approvedconfessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('his_her_name', models.CharField(blank=True, default='', max_length=100)),
                ('his_her_branch_year_hostel', models.CharField(blank=True, default='', max_length=100)),
                ('your_name_branch_year_hostel', models.CharField(blank=True, default='', max_length=100)),
                ('your_confession', models.TextField()),
                ('to_moderator', models.TextField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
