# Generated by Django 3.0.6 on 2020-05-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvedconfessions', '0002_auto_20200519_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedconfessions',
            name='confession',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approvedconfessions',
            name='to_moderator',
            field=models.TextField(blank=True, null=True),
        ),
    ]
