# Generated by Django 3.0.6 on 2020-05-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confession',
            options={'ordering': ['-created']},
        ),
    ]
