# Generated by Django 3.0.6 on 2020-05-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0002_auto_20200519_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='to_moderator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='confession',
            name='your_confession',
            field=models.TextField(blank=True, null=True),
        ),
    ]
